### ISSUE TITLE
Hide header search bar is not working in customizer

### ISSUE THREAD

**Issue by imranhsayed** [gsayed786/estella-lite#1]
**Customizer.php**
`$wp_customize->add_setting( 'estella_mod[hide_header_search_bar]', array(
          'sanitize_callback' => 'esc_url_raw',
          'capability'        => 'edit_theme_options',
          'default'           => '',
      ) );

```
    $wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'estella_mod[hide_header_search_bar]', array(
      'label'    =>   __( 'Hide Header Search Bar', 'estella' ),
      'type'     => 'checkbox',
      'section'  =>  'title_tagline',
      'settings' =>  'estella_mod[hide_header_search_bar]',
  ) ) );`
```

Customizer-front.php

'public static function header_search_bar() {
        if( estella_mod('hide_header_search_bar') == 1 ) {
            echo ".site-header .estella-search-bar{ display: none; }";
        }
    }

`public static function header_search_bar() {
        if( estella_mod('hide_header_search_bar') == 1 ) {
            echo ".site-header .estella-search-bar{ display: none; }";
        }
    }`

**Comment by mohdsayed** [comment]
Fixed already
